### PR TITLE
Not permitted to update new template

### LINKED ISSUE #121: Not permitted to update new template
**Describe the bug**
After creating a new reconciliation through the CLI, when I try to update that reconciliation I get an error.

 Response Error (422): {"downloadable_as_docx":"found unpermitted parameter: downloadable_as_docx for non externally managed template"} 
 You don't have the rights to update the previous parameters

I authorized the firm again but the issue persists.

**To Reproduce**
1. Create new recon. with the CLI
2. Update the main.liquid with some code
3. Run the update command through the CLI or try using development mode

**Expected behavior**
Recon. is updated in the firm

**Screenshots or Pull request**

**Desktop & CLI (please complete the following information):**
 - OS: macOS Sonoma 14.4
 - CLI version 1.26.4

**Additional context**

### PR DESCRIPTION
**Pull request by michieldegezelle**
## Description

Fix was made in line with what you proposed here: https://gitlab.silverfin.com/development/silverfin/-/issues/23082.

We will basically loop through all config items (with the reduce function), if the config item is present in the list of externally managed items (which is a new array) AND the config item externally_managed is put to false -> then the downloadable_as_docx will not be added to the final list of config items. 

This was verified within the be_market repo already, and seemed to work fine. downloadable_as_docx can be true/false, it won't be updated on the platform as long as externally_managed is put to false. 

Updating the template via the Silverfin extension doesn't work at the moment, but I assume this is because we still refer to the main version of the silverfin-cli code (thus excluding this check). Could you confirm this, and is there any way in which we can check this anyway? 

Fixes #121 

## Type of change

- [X] Bug fix
- [ ] New feature
- [ ] Breaking change

## Checklist

- [ ] README updated (if needed)
- [X] Version updated (if needed)
- [ ] Documentation updated (if needed)

### CODE REVIEW

**Review by AgustinSilverfin — COMMENTED** [review]
Update looks good and seems to be working. I have two comments to consider:

- Now the item is skipped but the user may not notice it. Can we show a message (using consola.warn maybe) indicating which items were skipped? Do you think that would be valuable? It could look like this:
 
image

- Let's consider and add some test for this update as well (considering we already have tests for `ReconciliationText#read`, we can look into expanding those to test this)

> Updating the template via the Silverfin extension doesn't work at the moment, but I assume this is because we still refer to the main version of the silverfin-cli code (thus excluding this check). Could you confirm this, and is there any way in which we can check this anyway?

Good point, the extension uses it's own version of the cli as a dependency. Releasing a new version of the cli won't impact automatically the extension. We need to go to the extension repository and bump the cli version when it's needed, and deploy it to vscode marketplace. We can look into this once this PR is released, and we go through the entire release process of the extension

**Comment by michieldegezelle** [comment]
@AgustinSilverfin Consola warning + test was added. Could you please do another review?

File: lib/templates/reconciliationText.js [hunk 1]
```diff
@@ -155,6 +155,9 @@ class ReconciliationText {
       // Skip externally managed items if externally_managed is false
       if (this.EXTERNALLY_MANAGED_ITEMS.includes(attribute) &&
         templateConfig.externally_managed === false) {
+        consola.warn(
+          `The following attributes were skipped because they can only be updated when the template is externally managed: ${this.EXTERNALLY_MANAGED_ITEMS.join(", ")}.`
+        );
```
Comment (AgustinSilverfin) [inline lib/templates/reconciliationText.js:160]: This is good, but if we include it here (in the iteration itself) it will be printed each time there is a skipped item.
Now it's only once because there is only one item `downloadable_as_docx`. But if we ever add more items the message will be repeated as many times as items are skipped

File: tests/lib/templates/reconciliationTexts.test.js [hunk 2]
```diff
@@ -452,5 +452,22 @@ describe("ReconciliationText", () => {
 
       expect(result.text_parts).toEqual([{ name: "empty_part", content: "" }]);
     });
+
+    it("should exclude downloadable_as_docx and show warning when externally_managed is false", () => {
```
Comment (AgustinSilverfin) [inline tests/lib/templates/reconciliationTexts.test.js:456]: This one looks good :+1: 
Maybe we can add a similar one testing that it's included when externally_managed is true?

File: lib/templates/reconciliationText.js (hunk 1 above)
Comment (michieldegezelle) [reply lib/templates/reconciliationText.js]: I have adjusted the logic so that the warning is only shown outside of the reduce.

File: tests/lib/templates/reconciliationTexts.test.js (hunk 2 above)
Comment (michieldegezelle) [reply tests/lib/templates/reconciliationTexts.test.js:456]: Positive scenario has been added as well
